travis:
  secure:
    BINSTAR_TOKEN: D0DxCXluIWKnzyDN+LmBozbsEFxVNaQqwj4OTe8TjpYlFWC8+VssMe+93u4Gwu41BE+dy9C36WeAqgb0C3gcnQYmHAV+GEcwXRhHSwM5QJRf5i4InUc8NSuOEsYfq+LRh3SUlELKoJvDJx73APJ+EQFmt5GopU0qRkV1uXylxrjSZWosKRtBHU5/AADj/kylq+L4yVQrAs4PFKrYV4w6flnfC9ziY3bhe3bfCYWpkFYiFKMJlest2URewpEdS26V5EuWQyjEHmarR/ci9Su+B3Aq7gDJWlIzayV1czfOazk+Apufrf1FvtMKSBTFPP2hS3aWkwFM5Mr4ELZi5XXaIo1ittNHZshFK8PGHjP6yfnseWrfVU/94zvpXCjbwnW9V9/dUKJRcaFR2rXRvVo0m5FXgkxp8W4c3kS9u+OhklUWKaVWCyEvKfG6ZnTpJDZlPQn5fGB2BtOsOnyw5OFWmIzyURnoTUmpQSX7N5BAjr2JoX1OyLUzshQzGeV5Jr7NdpxkYLyjU1cABJRRTld6mpJVwceT7dQR3W3AfA0GGn1JixBitfAiQfcA0T+Y/XFx0vs4tkVzPJOePn5Hyr3PbSwnLWz02LqKWdJ1rNWBgZbCr5/pfVHtjajNLJCGwrMHU4zz1facmRxbnEWwW/XbJjjiH2Ykx08OEQFdGEOs48k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
