travis:
  secure:
    BINSTAR_TOKEN: zdBEvIoL4ty3lDg7vymxYfL1ZOCxmHz/Gt85uguTNJ+bOh4RdXH59jnljG1eN/kuYp69XJevXMsWCQ8HfQ1Hq8c15V2sChLaVwTkaZTlhKhKjleXlm7/SeiyXeuf0JiGelbJlEQNDAwdpNJuGH7FdDi7bFJJ2BDtlkQpKFrU87gu2BvFdq02R+hEnL4ytMUC/4J8g+z8dYoMNHogMsfGtHSjZ04uap0ucGjt7e3av1mRXmPdPpLTXnFC6QhQaP7/Hx6xMSq7ir1V0JsdnQ8m+twV67EKF0IH0b6XXjEXGrLwKmkqShOYVcZMy4XdV+jxPB4collChp1u/MTI111JvIp5MhH1weDpW/nW4FKXuCYEoYxZELHL4NvI1qIwomApZugAMoYlvDiYS3hB2NW2xwkg5v82ew5E11GrVv/Do8BBixB6aQJQLb3EWNgsDWsWHW6s75WmGrOUOCvt5eszOYpxNjI9uWSUDnr0S2qcsww2/IJeZdgBXJ+cpegwViJ6h3zbMcOTVylSIKhA+9z6oX8beECR8gQTSv/altXw+8YUblHBS60BW2hUtCofXhwMglyDobL+1Pd2IIC7RtokNOcQyZadBI4J7y34FaakuCA+qrpx6aJLhANHIysFi5uB6+s4d1KfDOrqKdmvnPhwxKvwAP19Rebb3v/wZrIaHKI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
